"""What the assistant hands back: an answer made of real figures, where they came from, and any actions it can prepare.

A pure data description; formatting of the numbers is done by `ai_format` and the numbers come from the tools.
The assistant's words are assembled here from templates, never generated by a language model, so an answer can
only
contain what the database said.
"""

from dataclasses import dataclass, field
from typing import Any

# Answer statuses.
ANSWERED = "ANSWERED"
NO_DATA = "NO_DATA"  # the tool ran but there was nothing to report
NOT_AVAILABLE = "NOT_AVAILABLE"  # the application does not have this data (for example online orders)
NOT_UNDERSTOOD = "NOT_UNDERSTOOD"
NOT_CONFIGURED = "NOT_CONFIGURED"
REFUSED = "REFUSED"  # something the assistant will not do (another shop, a write, a database command)

NOT_CONFIGURED_TEXT = "AI Assistant is not configured."
NO_DATA_TEXT = "I don't have enough data to determine this."
RECOMMENDATION_BADGE = "AI Recommendation"


@dataclass
class Figure:
    label: str
    value: str
    note: str | None = None


@dataclass
class Table:
    columns: list[str]
    rows: list[list[str]]


@dataclass
class Proposal:
    """An action the assistant can prepare. Showing it changes nothing; the person chooses to create the draft."""

    kind: str  # an AiActionKind value
    feature: str
    label: str
    payload: dict[str, Any]


@dataclass
class Answer:
    status: str
    tool: str | None
    title: str
    message: str
    figures: list[Figure] = field(default_factory=list)
    table: Table | None = None
    sources: list[str] = field(default_factory=list)
    period: dict[str, str] | None = None
    notes: list[str] = field(default_factory=list)
    badges: list[str] = field(default_factory=list)
    proposals: list[Proposal] = field(default_factory=list)
    export: dict[str, Any] | None = None  # {"kind": ..., "filters": {...}} for the existing export buttons
    follow_ups: list[str] = field(default_factory=list)
    provider_used: bool = False
