"""Online store

* `store_settings`, `store_listings`: a shop's public storefront and which products it lists.
* `online_orders`, `online_order_items`, `online_order_events`: customer orders (requests; nothing moves until DELIVERED creates the
  ordinary sale). The events table is insert-only.
* No new permission: the store's setup uses the existing `STORE_SETTINGS_MANAGE` (already held by the OWNER and MANAGER roles).

Revision ID: 0022
Revises: 0021
Create Date: 2026-09-24 19:48:44.456167
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

INSERT_ONLY = ["online_order_events"]


def _create_triggers() -> None:
    dialect = op.get_bind().dialect.name
    for table in INSERT_ONLY:
        if dialect == "sqlite":
            for action in ("UPDATE", "DELETE"):
                op.execute(
                    f"CREATE TRIGGER trg_{table}_no_{action.lower()} BEFORE {action} ON {table} "
                    f"BEGIN SELECT RAISE(ABORT, '{table} is insert-only'); END"
                )
        elif dialect == "postgresql":
            op.execute(
                f"CREATE TRIGGER trg_{table}_insert_only BEFORE UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION kirana_forbid_change()"
            )


def _drop_triggers() -> None:
    dialect = op.get_bind().dialect.name
    for table in INSERT_ONLY:
        if dialect == "sqlite":
            for action in ("update", "delete"):
                op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_no_{action}")
        elif dialect == "postgresql":
            op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_insert_only ON {table}")


# revision identifiers, used by Alembic.
revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_settings",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("shop_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("is_open", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("accepts_cod", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("accepts_upi", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("delivery_enabled", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("pickup_enabled", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("min_order_amount", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.Column("announcement", sa.String(length=300), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(trim(display_name)) > 0", name=op.f("ck_store_settings_display_name_not_blank")
        ),
        sa.CheckConstraint("length(trim(slug)) > 0", name=op.f("ck_store_settings_slug_not_blank")),
        sa.CheckConstraint("min_order_amount >= 0", name=op.f("ck_store_settings_min_order_non_negative")),
        sa.ForeignKeyConstraint(["shop_id"], ["shops.id"], name=op.f("fk_store_settings_shop_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_settings")),
        sa.UniqueConstraint("shop_id", "id", name=op.f("uq_store_settings_shop_id_id")),
        sa.UniqueConstraint("shop_id", name=op.f("uq_store_settings_shop_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_store_settings_slug")),
    )
    op.create_table(
        "store_listings",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("shop_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("product_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("is_visible", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id", "product_id"],
            ["products.shop_id", "products.id"],
            name=op.f("fk_store_listings_shop_id_product_id"),
        ),
        sa.ForeignKeyConstraint(["shop_id"], ["shops.id"], name=op.f("fk_store_listings_shop_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_listings")),
        sa.UniqueConstraint("shop_id", "id", name=op.f("uq_store_listings_shop_id_id")),
        sa.UniqueConstraint("shop_id", "product_id", name=op.f("uq_store_listings_shop_id_product_id")),
    )
    op.create_table(
        "online_orders",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("shop_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("order_no", sa.String(length=30), nullable=False),
        sa.Column("tracking_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PLACED",
                "ACCEPTED",
                "PREPARING",
                "READY",
                "OUT_FOR_DELIVERY",
                "DELIVERED",
                "REJECTED",
                "CANCELLED",
                name="online_order_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "fulfilment_type",
            sa.Enum(
                "DELIVERY",
                "PICKUP",
                name="online_order_fulfilment",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            sa.Enum("COD", "UPI", name="online_order_payment", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("customer_name", sa.String(length=120), nullable=False),
        sa.Column("customer_phone", sa.String(length=20), nullable=False),
        sa.Column("delivery_address", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=300), nullable=True),
        sa.Column("total_amount", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("sale_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("sale_total", sa.BigInteger(), nullable=True),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("decision_reason", sa.String(length=300), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "fulfilment_type <> 'DELIVERY' OR (delivery_address IS NOT NULL AND length(trim(delivery_address)) > 0)",
            name=op.f("ck_online_orders_delivery_needs_address"),
        ),
        sa.CheckConstraint(
            "status <> 'DELIVERED' OR sale_id IS NOT NULL", name=op.f("ck_online_orders_delivered_has_sale")
        ),
        sa.CheckConstraint(
            "length(trim(customer_name)) > 0", name=op.f("ck_online_orders_customer_name_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(customer_phone)) > 0", name=op.f("ck_online_orders_customer_phone_not_blank")
        ),
        sa.CheckConstraint("total_amount > 0", name=op.f("ck_online_orders_total_positive")),
        sa.ForeignKeyConstraint(
            ["shop_id", "customer_id"],
            ["customers.shop_id", "customers.id"],
            name=op.f("fk_online_orders_shop_id_customer_id"),
        ),
        sa.ForeignKeyConstraint(
            ["shop_id", "decided_by"],
            ["users.shop_id", "users.id"],
            name=op.f("fk_online_orders_shop_id_decided_by"),
        ),
        sa.ForeignKeyConstraint(
            ["shop_id", "sale_id"],
            ["sales.shop_id", "sales.id"],
            name=op.f("fk_online_orders_shop_id_sale_id"),
        ),
        sa.ForeignKeyConstraint(["shop_id"], ["shops.id"], name=op.f("fk_online_orders_shop_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_online_orders")),
        sa.UniqueConstraint("shop_id", "id", name=op.f("uq_online_orders_shop_id_id")),
        sa.UniqueConstraint(
            "shop_id", "idempotency_key", name=op.f("uq_online_orders_shop_id_idempotency_key")
        ),
        sa.UniqueConstraint("shop_id", "order_no", name=op.f("uq_online_orders_shop_id_order_no")),
        sa.UniqueConstraint("shop_id", "sale_id", name=op.f("uq_online_orders_shop_id_sale_id")),
        sa.UniqueConstraint("tracking_hash", name=op.f("uq_online_orders_tracking_hash")),
    )
    with op.batch_alter_table("online_orders", schema=None) as batch_op:
        batch_op.create_index("ix_online_orders_shop_phone", ["shop_id", "customer_phone"], unique=False)
        batch_op.create_index("ix_online_orders_shop_status", ["shop_id", "status"], unique=False)

    op.create_table(
        "online_order_events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("shop_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("order_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("actor", sa.String(length=10), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id", "order_id"],
            ["online_orders.shop_id", "online_orders.id"],
            name=op.f("fk_online_order_events_shop_id_order_id"),
        ),
        sa.ForeignKeyConstraint(["shop_id"], ["shops.id"], name=op.f("fk_online_order_events_shop_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_online_order_events")),
        sa.UniqueConstraint("shop_id", "id", name=op.f("uq_online_order_events_shop_id_id")),
    )
    with op.batch_alter_table("online_order_events", schema=None) as batch_op:
        batch_op.create_index("ix_online_order_events_order", ["shop_id", "order_id"], unique=False)

    op.create_table(
        "online_order_items",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("shop_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("order_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("product_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("unit_label", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("unit_price", sa.BigInteger(), nullable=False),
        sa.Column("line_total", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_online_order_items_quantity_positive")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_online_order_items_unit_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["shop_id", "order_id"],
            ["online_orders.shop_id", "online_orders.id"],
            name=op.f("fk_online_order_items_shop_id_order_id"),
        ),
        sa.ForeignKeyConstraint(
            ["shop_id", "product_id"],
            ["products.shop_id", "products.id"],
            name=op.f("fk_online_order_items_shop_id_product_id"),
        ),
        sa.ForeignKeyConstraint(["shop_id"], ["shops.id"], name=op.f("fk_online_order_items_shop_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_online_order_items")),
        sa.UniqueConstraint("shop_id", "id", name=op.f("uq_online_order_items_shop_id_id")),
    )
    with op.batch_alter_table("online_order_items", schema=None) as batch_op:
        batch_op.create_index("ix_online_order_items_order", ["shop_id", "order_id"], unique=False)

    # ### end Alembic commands ###
    _create_triggers()


def downgrade() -> None:
    _drop_triggers()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("online_order_items", schema=None) as batch_op:
        batch_op.drop_index("ix_online_order_items_order")

    op.drop_table("online_order_items")
    with op.batch_alter_table("online_order_events", schema=None) as batch_op:
        batch_op.drop_index("ix_online_order_events_order")

    op.drop_table("online_order_events")
    with op.batch_alter_table("online_orders", schema=None) as batch_op:
        batch_op.drop_index("ix_online_orders_shop_status")
        batch_op.drop_index("ix_online_orders_shop_phone")

    op.drop_table("online_orders")
    op.drop_table("store_listings")
    op.drop_table("store_settings")
    # ### end Alembic commands ###
